### ISSUE TITLE
The item you are looking for is currently not available

### ISSUE THREAD

**Issue by bjornnorlen** [Ucommercenet/Avenue-Clothing-For-Umbraco#64]
Umbraco version: 8.9.0
Ucommerce version: 9.3.1.20275

I've downloaded the Ucommerce package from the Master branch and added the folders for Api, controllers, enums, img, models, search and views to a new Umbraco installation. I've managed to set up a store in the backoffice, added categories and products and make them render on the front-end. However, when I visit a product-page I'm not able to render the "Add to basket" button. In the product.cshtml view there is an if-statement that checks if ordering is allowed, which if true should render the button, otherwise there's a messga ethat ordering isn't allowed:

```
@if (Model.ProductViewModel.IsOrderingAllowed)
{
       <!--Button is rendered here--> 
}
 else
{
      <p>Sorry, the item you are looking for is not currently available.</p>
}
```

![Img1](https://user-images.githubusercontent.com/19406378/99545707-f881af00-29b5-11eb-9ad8-a8f25eeb0a88.png)
![Img3](https://user-images.githubusercontent.com/19406378/99545720-fa4b7280-29b5-11eb-930a-c89feaf3bb02.png)

IsOrderingAllowed derives from the AllowOrdering property. This exists in the [dbo].[uCommerce_Product] table in the database and is zero for the products I've added but it is nowhere to be found in the Ucommerce editor. I've tried added it as a definition to my product but I only receive the message which states that the item could not be saved. I've also signed into the demo store over at https://umbracodemo1.ucommerce.net/ to try add a new product but it's the same issue. The "Add to basket" isn't rendered. Any idea why that is?

/Björn

**Comment by DavidKelemen** [comment]
Hi!

Yes, this is a known issue. With the core platform, we are moving away from having these types of properties on the product (hence it missing from the UI), and letting partners decide how this process should work (eg. adding a definition field for it). 

It's just that we haven't gotten around to updating avenue clothing for it, unfortunatley. What this means for you is, if you want to have the option of making a product not purchasable, you should make a definition field for it, and use that definition field's value in the if statement instead of the allowOrdering property. If you don't need this, you can just remove the check for it entirely.

Hope this helps!

**Comment by DavidKelemen** [comment]
Oh, and to address the error from the screenshot, I believe that is because spaces are not allowed in the names of definition fields 😀

**Comment by bjornnorlen** [comment]
@DavidKelemen Thank you for the response. Any more properties that one should be aware of that's being removed? 😁 
Haha yeah, i was suspecting that I had spelled it wrong, but earlier I also has tried spelling it without any space "AllowOrdering" and it still hadn't worked 😄 Anyway, I removed that part of the code so now it's working!
