### ISSUE TITLE
Variant properties not rendering on front-end/can't add to basket/

### ISSUE THREAD

**Issue by bjornnorlen** [Ucommercenet/Avenue-Clothing-For-Umbraco#65]
Hi,
I've spun up my own Umbraco installation, installed the latest version of Ucommerce and added the following folders to the solution from the Avenue Clothing repository:

- API
- Controllers
- css
- Enums
- Img
- Models
- scripts
- Search
- Views

I've some issues with rendering a products' variant property on the product page for a product, for example collar size as in the demo store at https://umbracodemo1.ucommerce.net/. In the backoffice I've added a product type called "Skjortor" and it has a proprty called "Storlek" which is a variant. On the product I've created two variants and added the information I want. However, it isn't rendered on the front-end. The issue seems to originate from the ProductController, in the MapProductProperties() method. uniqueVariants is null when I'm inspecting it. I guess it's supposed to receive the values from the userDefinedfields property in a variant coming from the input parameter in the method but there seems to be none. Any idea what's going on?

![Img1](https://user-images.githubusercontent.com/19406378/100361261-3d32c900-2ffa-11eb-960d-ab974f9cda1c.png)
![Img2](https://user-images.githubusercontent.com/19406378/100361263-3e63f600-2ffa-11eb-8800-0f4e315dbcc7.png)
![Img3](https://user-images.githubusercontent.com/19406378/100361265-3e63f600-2ffa-11eb-94f3-576913836e32.png)
![Img4](https://user-images.githubusercontent.com/19406378/100361268-3efc8c80-2ffa-11eb-9abf-2592fe140ec4.png)
![Img5](https://user-images.githubusercontent.com/19406378/100361269-3efc8c80-2ffa-11eb-9df5-76b5890fc80a.png)

Kind regards
Björn

**Comment by bjornnorlen** [comment]
I'm starting to believe there might be something wrong with the way you obtain properties, as [described in the documentation](https://docs.ucommerce.net/ucommerce/v9.3/getting-started/catalog-foundation/Product-Page.html). I've created a test-property that isn't a variant but I can't obtain that value either. The value of the variable "test" in the image below is null when visiting a product:

![Img1](https://user-images.githubusercontent.com/19406378/100614563-9cece500-3316-11eb-8afc-faf4ff339e1f.png)
![Img2](https://user-images.githubusercontent.com/19406378/100614570-9eb6a880-3316-11eb-99b4-4970ed0024ce.png)

**Comment by nielsen10** [comment]
Hi @bjornnorlen 

It looks like you forgot to add the custom field to your index definition, can you please try that out and see if that helps? :)

https://docs.ucommerce.net/ucommerce/v9.4.2/search-and-indexing/index-definitions.html

When using a Ucommerce.Search.Models.Product the information is fetched from the index, which is built based on IndexDefinition. This means when you add custom stuff to your Product, you need to add it to the IndexDefinition to make it show up in the Index.

Hope that makes sense, otherwise please let me know :)

Regards Anders
Ucommerce Customer Succes Agent

**Comment by bjornnorlen** [comment]
@nielsen10 Sorry for the late reply. During my post I had not created a index definition for my custom field. I've added it since but it was still not working. Since then I've installed Umbraco on another machine, installed uCommerce and added the folders mentioned above to see if I could get it working but the problem remains. I've added a product definition field called "Storlek" to one of the product types you get out of the box and added values to that field for the product. This time I also made sure that I had added the field to my index definition but the variant property still isn't rendering. Any help is much appriciated.

Kind regards
Björn

![image](https://user-images.githubusercontent.com/19406378/134769169-84cc9601-4592-4073-9b5c-1b71ee0eb057.png)

![image](https://user-images.githubusercontent.com/19406378/134769194-d057bfa6-7d22-4f8f-8fb4-192ddaf7f272.png)

![image](https://user-images.githubusercontent.com/19406378/134769201-77770620-a5b1-4581-9a55-6875fb848ea8.png)

![image](https://user-images.githubusercontent.com/19406378/134769216-c76edaa9-3a51-4145-80e0-17acf6e6f5a5.png)

![image](https://user-images.githubusercontent.com/19406378/134769221-696ca6a2-fe68-4859-b11e-550e007aa596.png)

**Comment by nielsen10** [comment]
It looks like this is because you added the info to the product, then you added the definition to the index. That means the info is still not in the index.
If you go to another product, and add text to the field, it will be indexed when saving, and then you should be able to see it in the front end.
To get the product you edited prior to adding the definition to the index, you can either save it again, or run the scratchindexer. Read more about that here:
https://docs.ucommerce.net/ucommerce/v9.5/search-and-indexing/Running-the-scratch-indexer.html
